server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

# 自定义配置
web:
  # 文件上传路径
  upload-path: H:\\temp\\upload\\

# 用户最多所能拥有的地址数目
user:
  address:
    max-count: 20
